//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerLedger
    {
        public int CustomerLedgerId { get; set; }
        public string CustomerLedgerCode { get; set; }
        public string CustomerLedgerName { get; set; }
        public string CustomerLedgerShortName { get; set; }
        public string Address { get; set; }
        public string ContactPerson { get; set; }
        public string Mobile { get; set; }
        public string Pager { get; set; }
        public string Fax { get; set; }
        public string OfficePhone { get; set; }
        public string ResidentPhone { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<decimal> OpeningBal { get; set; }
        public string CreditDebit { get; set; }
        public string TaxRetail { get; set; }
        public bool Status { get; set; }
        public int ZSMId { get; set; }
        public int ASMId { get; set; }
        public int RSMId { get; set; }
        public int AreaId { get; set; }
        public int SalesManId { get; set; }
        public int RouteId { get; set; }
        public string DLNo { get; set; }
        public string TINNo { get; set; }
        public string CSTNo { get; set; }
        public string Day { get; set; }
        public int CreditLimit { get; set; }
        public string BankName { get; set; }
        public string BankArea { get; set; }
        public string CloseDay { get; set; }
        public Nullable<int> RateTypeID { get; set; }
        public bool IsLessExcise { get; set; }
        public int CustomerTypeID { get; set; }
        public int InterestTypeID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual PersonRouteMaster PersonRouteMaster { get; set; }
        public virtual CustomerType CustomerType { get; set; }
        public virtual InterestType InterestType { get; set; }
        public virtual PersonRouteMaster PersonRouteMaster1 { get; set; }
        public virtual PersonRouteMaster PersonRouteMaster2 { get; set; }
        public virtual PersonRouteMaster PersonRouteMaster3 { get; set; }
        public virtual PersonRouteMaster PersonRouteMaster4 { get; set; }
        public virtual PersonRouteMaster PersonRouteMaster5 { get; set; }
    }
}
