//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Master
    {
        public int ID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string CompCode { get; set; }
        public string ALTName { get; set; }
        public string Size { get; set; }
        public Nullable<double> ConvRate { get; set; }
        public Nullable<double> Case_QTY { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<double> PRate { get; set; }
        public Nullable<double> SRate { get; set; }
        public double MRP { get; set; }
        public Nullable<double> SPLRate { get; set; }
        public Nullable<double> WSRate { get; set; }
        public Nullable<double> SExcise { get; set; }
        public Nullable<double> SC { get; set; }
        public Nullable<double> STax { get; set; }
        public Nullable<double> PExcise { get; set; }
        public Nullable<double> Scheme1 { get; set; }
        public Nullable<double> Scheme2 { get; set; }
        public string UPC { get; set; }
        public string Half { get; set; }
        public string QTR { get; set; }
        public Nullable<double> SPLDIS { get; set; }
        public Nullable<double> DISQTY { get; set; }
        public Nullable<double> PSPLDIS { get; set; }
        public Nullable<double> PDIS { get; set; }
        public Nullable<double> PSC { get; set; }
        public Nullable<double> PTax { get; set; }
        public string Location { get; set; }
        public string SType { get; set; }
        public Nullable<double> MAX_QTY { get; set; }
        public Nullable<int> MIN_STOCK { get; set; }
        public Nullable<int> MAX_STOCK { get; set; }
        public Nullable<double> FIXDIS { get; set; }
        public Nullable<double> MAXDIS { get; set; }
        public bool Status { get; set; }
    }
}
