//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemMaster()
        {
            this.CustomerCompanyDiscountRef = new HashSet<CustomerCompanyDiscountRef>();
            this.SupplierCompanyDiscountRef = new HashSet<SupplierCompanyDiscountRef>();
        }
    
        public int ItemID { get; set; }
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public int CompanyID { get; set; }
        public Nullable<double> ConversionRate { get; set; }
        public string ShortName { get; set; }
        public string Packing { get; set; }
        public Nullable<double> PurchaseRate { get; set; }
        public double MRP { get; set; }
        public Nullable<double> SaleRate { get; set; }
        public Nullable<double> SpecialRate { get; set; }
        public Nullable<double> WholeSaleRate { get; set; }
        public Nullable<double> SaleExcise { get; set; }
        public Nullable<double> SurchargeOnSale { get; set; }
        public Nullable<double> TaxOnSale { get; set; }
        public Nullable<double> Scheme1 { get; set; }
        public Nullable<double> Scheme2 { get; set; }
        public Nullable<double> PurchaseExcise { get; set; }
        public string UPC { get; set; }
        public bool IsHalfScheme { get; set; }
        public bool IsQTRScheme { get; set; }
        public Nullable<double> SpecialDiscount { get; set; }
        public Nullable<double> SpecialDiscountOnQty { get; set; }
        public bool IsFixedDiscount { get; set; }
        public Nullable<double> FixedDiscountRate { get; set; }
        public Nullable<double> MaximumQty { get; set; }
        public Nullable<double> MaximumDiscount { get; set; }
        public Nullable<double> SurchargeOnPurchase { get; set; }
        public Nullable<double> TaxOnPurchase { get; set; }
        public Nullable<double> DiscountRecieved { get; set; }
        public Nullable<double> SpecialDiscountRecieved { get; set; }
        public Nullable<double> QtyPerCase { get; set; }
        public string Location { get; set; }
        public Nullable<int> MinimumStock { get; set; }
        public Nullable<int> MaximumStock { get; set; }
        public int SaleTypeId { get; set; }
        public int PurchaseTypeId { get; set; }
        public bool Status { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string BATCH { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<double> OpeningQty { get; set; }
        public Nullable<double> ClosingQty { get; set; }
        public string SaltCode { get; set; }
        public string SaltName { get; set; }
    
        public virtual AccountLedgerMaster AccountLedgerMaster { get; set; }
        public virtual AccountLedgerMaster AccountLedgerMaster1 { get; set; }
        public virtual CompanyMaster CompanyMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerCompanyDiscountRef> CustomerCompanyDiscountRef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierCompanyDiscountRef> SupplierCompanyDiscountRef { get; set; }
    }
}
