//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_MASTER
    {
        public string COMPCD { get; set; }
        public string ACNO { get; set; }
        public string ACNAME { get; set; }
        public Nullable<double> CONVRATE { get; set; }
        public string ALT_NAME { get; set; }
        public string SIZE { get; set; }
        public Nullable<double> PRATE { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<double> SRATE { get; set; }
        public Nullable<double> SPLRATE { get; set; }
        public Nullable<double> WSRATE { get; set; }
        public Nullable<double> EXCISES { get; set; }
        public Nullable<double> SC { get; set; }
        public Nullable<double> STAX { get; set; }
        public Nullable<double> SCHEME1 { get; set; }
        public Nullable<double> SCHEME2 { get; set; }
        public Nullable<double> EXCISEP { get; set; }
        public string UPC { get; set; }
        public string HALF { get; set; }
        public string QTR { get; set; }
        public Nullable<double> SPLDIS { get; set; }
        public Nullable<double> DISQTY { get; set; }
        public Nullable<double> PSPLDIS { get; set; }
        public Nullable<double> PDIS { get; set; }
        public Nullable<double> PSC { get; set; }
        public Nullable<double> PTAX { get; set; }
        public Nullable<double> CASE_QTY { get; set; }
        public string LOCATION { get; set; }
        public string STYPE { get; set; }
        public Nullable<double> MAX_QTY { get; set; }
        public Nullable<int> MIN_STOCK { get; set; }
        public Nullable<int> MAX_STOCK { get; set; }
        public Nullable<double> RATE { get; set; }
        public Nullable<double> FIXDIS { get; set; }
        public Nullable<double> MAXDIS { get; set; }
        public bool STATUS { get; set; }
    }
}
