//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseSaleBookHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseSaleBookHeader()
        {
            this.BillOutStandings = new HashSet<BillOutStandings>();
            this.BillOutStandingsAudjustment = new HashSet<BillOutStandingsAudjustment>();
            this.BillOutStandingsAudjustment1 = new HashSet<BillOutStandingsAudjustment>();
            this.FIFO = new HashSet<FIFO>();
            this.PurchaseSaleBookLineItem = new HashSet<PurchaseSaleBookLineItem>();
            this.TRN = new HashSet<TRN>();
        }
    
        public long PurchaseSaleBookHeaderID { get; set; }
        public string VoucherNumber { get; set; }
        public string VoucherTypeCode { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string PurchaseBillNo { get; set; }
        public string LedgerType { get; set; }
        public string LedgerTypeCode { get; set; }
        public Nullable<double> Amount01 { get; set; }
        public Nullable<double> Amount02 { get; set; }
        public Nullable<double> Amount03 { get; set; }
        public Nullable<double> Amount04 { get; set; }
        public Nullable<double> Amount05 { get; set; }
        public Nullable<double> Amount06 { get; set; }
        public Nullable<double> Amount07 { get; set; }
        public Nullable<double> SGST01 { get; set; }
        public Nullable<double> SGST02 { get; set; }
        public Nullable<double> SGST03 { get; set; }
        public Nullable<double> SGST04 { get; set; }
        public Nullable<double> SGST05 { get; set; }
        public Nullable<double> SGST06 { get; set; }
        public Nullable<double> SGST07 { get; set; }
        public Nullable<double> IGST01 { get; set; }
        public Nullable<double> IGST02 { get; set; }
        public Nullable<double> IGST03 { get; set; }
        public Nullable<double> IGST04 { get; set; }
        public Nullable<double> IGST05 { get; set; }
        public Nullable<double> IGST06 { get; set; }
        public Nullable<double> IGST07 { get; set; }
        public Nullable<double> CGST01 { get; set; }
        public Nullable<double> CGST02 { get; set; }
        public Nullable<double> CGST03 { get; set; }
        public Nullable<double> CGST04 { get; set; }
        public Nullable<double> CGST05 { get; set; }
        public Nullable<double> CGST06 { get; set; }
        public Nullable<double> CGST07 { get; set; }
        public double TotalTaxAmount { get; set; }
        public Nullable<double> SurchargeAmount { get; set; }
        public Nullable<double> TotalBillAmount { get; set; }
        public Nullable<double> TotalCostAmount { get; set; }
        public Nullable<double> TotalGrossAmount { get; set; }
        public Nullable<double> TotalSchemeAmount { get; set; }
        public Nullable<double> TotalDiscountAmount { get; set; }
        public Nullable<double> OtherAmount { get; set; }
        public Nullable<int> ZSMId { get; set; }
        public Nullable<int> ASMId { get; set; }
        public Nullable<int> RSMId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> SalesManId { get; set; }
        public Nullable<int> RouteId { get; set; }
        public string FreshBreakageExcess { get; set; }
        public string ReturnBillNo { get; set; }
        public Nullable<System.DateTime> ReturBillDate { get; set; }
        public Nullable<int> CustomerTypeId { get; set; }
        public string LocalCentral { get; set; }
        public Nullable<int> RateTypeId { get; set; }
        public string OrderNumber { get; set; }
        public string ChallanNumber { get; set; }
        public string Message { get; set; }
        public string Deliveryddress { get; set; }
        public string DeliveredBy { get; set; }
        public string CourierName { get; set; }
        public Nullable<System.DateTime> CourierDate { get; set; }
        public Nullable<double> CourierWeight { get; set; }
        public Nullable<int> PurchaseSaleEntryFormID { get; set; }
        public Nullable<double> LastBalance { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOutStandings> BillOutStandings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOutStandingsAudjustment> BillOutStandingsAudjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillOutStandingsAudjustment> BillOutStandingsAudjustment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FIFO> FIFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseSaleBookLineItem> PurchaseSaleBookLineItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN> TRN { get; set; }
    }
}
