//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseBookHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseBookHeader()
        {
            this.PurchaseBookLineItem = new HashSet<PurchaseBookLineItem>();
        }
    
        public int ID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string CompanyCode { get; set; }
        public string InvoiceNumber { get; set; }
        public string AccountLedgerCode { get; set; }
        public double TotalAmount { get; set; }
        public Nullable<double> Excise { get; set; }
        public Nullable<double> HSCM { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> Net { get; set; }
        public Nullable<double> PurAmount1 { get; set; }
        public Nullable<double> VAT1 { get; set; }
        public Nullable<double> PurAmount2 { get; set; }
        public Nullable<double> VAT2 { get; set; }
        public Nullable<double> ExemptedAmount { get; set; }
        public Nullable<double> OtherAmount { get; set; }
        public Nullable<double> InvoiceAmount { get; set; }
        public string Narration1 { get; set; }
        public string Narration2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseBookLineItem> PurchaseBookLineItem { get; set; }
    }
}
