//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierLedger
    {
        public int SupplierLedgerId { get; set; }
        public string SupplierLedgerCode { get; set; }
        public string SupplierLedgerName { get; set; }
        public string SupplierLedgerShortName { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string OfficePhone { get; set; }
        public string ResidentPhone { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<decimal> OpeningBal { get; set; }
        public string CreditDebit { get; set; }
        public string TaxRetail { get; set; }
        public bool Status { get; set; }
        public int AreaId { get; set; }
        public string DLNo { get; set; }
        public string TINNo { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string SupplierLedgerShortDesc { get; set; }
        public int PurchaseTypeID { get; set; }
        public string ContactPerson { get; set; }
    
        public virtual AccountLedgerMaster AccountLedgerMaster { get; set; }
        public virtual PersonRouteMaster PersonRouteMaster { get; set; }
    }
}
