//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDAL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempPurchaseBookLineItem
    {
        public int ID { get; set; }
        public int PurchaseBookHeaderID { get; set; }
        public string ItemCode { get; set; }
        public string BatchNo { get; set; }
        public string PurchaseTaxType { get; set; }
        public int Quantity { get; set; }
        public Nullable<int> FreeQuantity { get; set; }
        public Nullable<double> Scheme1 { get; set; }
        public Nullable<double> Scheme2 { get; set; }
        public bool IsHalfScheme { get; set; }
        public double Rate { get; set; }
        public double Amount { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> SpecialDiscount { get; set; }
        public Nullable<double> VolumeDiscount { get; set; }
        public Nullable<double> MRP { get; set; }
        public Nullable<double> Excise { get; set; }
        public Nullable<System.DateTime> Expiry { get; set; }
        public Nullable<double> TaxOnPurchase { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual TempPurchaseBookHeader TempPurchaseBookHeader { get; set; }
    }
}
